---
title: "A4"
author: "Antonio Roldan Andrade"
date: "2026-01-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(stringr)
```

# Actividad 4

## 1. Preprocesamiento

### 1.1 Nombres de las variables

```{r, echo=TRUE}

# Comenzamos por la carga del diccionario CSV
csv_location <- "Findata.csv"
dataSet <- read.csv(csv_location, sep = ",")

# Realizamos las modificaciones pertinentes de los nombres: 
dataSet <- dataSet %>%
  rename_with(~ 
                str_remove(., "\\.+$") %>% # Elimina los puntos al final nombres de variables
                str_replace_all(., "\\.+", "_") %>% # Sustituye los puntos dentro por _
                str_replace_all("__+", "_") # Si hay dos puntos seguidos, reemplazadlos por un único guion bajo.
                
              )
# Comprobamos 
names(dataSet)

```

### 1.2 Variables Weight_kg y Height_m
```{r, echo=TRUE}
# Comprobamos tipos de variables (con glympse, glimpse(dataSet))
# Se puede percibir que la columna Weight..kg. es incorrecta (marcada como character)

# Weight
dataSet <- dataSet %>%
  mutate(
    # Aseguramos que sea texto para limpiar, quitamos espacios
    Weight_kg = str_to_lower(as.character(Weight_kg)),
    
    # Si contiene "b para aplicar la conversión
    Weight_kg = case_when(
      str_detect(Weight_kg, "lb") ~ as.numeric(str_extract(Weight_kg, "[0-9.]+")) / 2.20,
      TRUE ~ as.numeric(str_extract(Weight_kg, "[0-9.]+"))
    )
  )
# Comprobamos datos
head(dataSet$Weight_kg)

# Height
dataSet <- dataSet %>%
  mutate(
    Height_m = str_to_lower(as.character(Height_m)),
    
    # Si contiene feet (') o inches (")
    Height_m = case_when(
      str_detect(Height_m, "'|\"|ft|in") ~ {
        # Extraemos todos los números encontrados
        numeros <- str_extract_all(Height_m, "[0-9.]+")
        # El primero son pies, el segundo pulgadas
        pies <- as.numeric(sapply(numeros, function(x) x[1]))
        pulgadas <- as.numeric(sapply(numeros, function(x) ifelse(length(x) > 1, x[2], 0)))
        # Convertimos: (pies * 12 + pulgadas) / 39.37
        (pies * 12 + pulgadas) / 39.37
      },
      # Si es numérico o solo necesita conversión de pulgadas a metros
      TRUE ~ as.numeric(str_extract(Height_m, "[0-9.]+"))
    )
  )

# Comprobamos datos
head(dataSet$Height_m)

```


### Valores Ausentes y Atípicos
```{r,echo=TRUE}
# Weight

# Valores Ausentes
na_weight <- sum(is.na(dataSet$Weight_kg))

# Valores Atípicos 
out_weight <- length(boxplot.stats(dataSet$Weight_kg)$out)

cat("Peso - Ausentes:", na_weight, "| Atípicos:", out_weight)

# Height
na_height <- sum(is.na(dataSet$Height_m))

# Valores Atípicos
out_height <- length(boxplot.stats(dataSet$Height_m)$out)

cat("Altura - Ausentes:", na_height, "| Atípicos:", out_height)

```
























